import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";

import { Roboto, Big_Shoulders } from "next/font/google";

const bigShoulders = Big_Shoulders({
  subsets: ["latin"],
  variable: "--font-big-shoulders",
  fallback: ["Arial", "sans-serif"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
  fallback: ["Arial", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bigShoulders.variable} ${roboto.variable}`}>
      <body className="font-roboto min-h-full flex flex-col">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
